---
- name: Playbook para instalar la pila frontend
  hosts: front
  become: yes

  tasks:

  - name: Añadimos las variables
    ansible.builtin.include_vars:
      ../vars/variables.yml

  - name: Actualizar los repositorios
    apt:
      update_cache: yes

  - name: Instalar el servidor web Apache
    apt:
      name: apache2
      state: present

  - name: Instalar PHP 
    apt:
      name: "{{ php_paquetes }}"
      state: present


  - name: Movemos los archivos de configuración a /etc/apache2/sites-availeble
    copy:
      src: /home/ubuntu/practica9V/fase2/conf/000-default.conf
      dest: /etc/apache2/sites-available/

  - name: Movemos el dir.conf
    copy:
      src: /home/ubuntu/practica9V/fase2/conf/dir.conf
      dest: /etc/apache2/mods-available

#--------------------------------------------------------------

  - name: Instalamos el módulo rewrite
    apache2_module:
        name: rewrite
        state: present

  - name: Reiniciamos el servidor apache
    service:
      name: apache2
      state: restarted 