---
- name: Playbook para instalar la pila nfs
  hosts: nfs
  become: yes

  tasks:

  - name: Actualizar los repositorios
    apt:
      update_cache: yes

  - name: Instalación nfs server
    apt:
      name: nfs-kernel-server

  - name: Creamos el directorio
    ansible.builtin.file:
      path: /var/www/html
      state: directory
      mode: 0755
      owner: nobody
      group: nogroup

  - name: Pasamos el archivo de conf a /etc/exports
    copy:
      src: /home/ubuntu/practica9V/fase2/conf/exports
      dest: /etc/exports

  - name: Eliminamos los archivos clonados innecesarios.
    file:
      path: /tmp/archivos

  - name: Reiniciamos el servidor servidor nfs
    service:
      name: nfs-kernel-server
      state: restarted 
