---
DB_HOST_PRIVATE_IP: localhost
DB_NAME: db_name
DB_USER: db_user
DB_PASS: db_pass

WP_HOME: https://practica9dmpverda.ddns.net
WP_SITEURL: https://practica9dmpverda.ddns.net

EMAIL: pepico51226@gmail.com
DOMAIN: practica9dmpverda.ddns.net


php_paquetes:
  - php
  - libapache2-mod-php 
  - php-mysql