---
- name: Playbook para instalar  wordpress
  hosts: front
  become: yes

  vars:
   - NFS_SERVER_IP_PRIVATE: 172.31.64.127
  tasks: 


  - name: Actualizar los repositorios
    apt:
      update_cache: yes

  - name: Instalamos el cliente nfs
    apt:
      name: nfs-common
      state: present

 # - name: Mount NFS volumes with noauto according to boot option
 #   ansible.posix.mount:
 #     path: /var/www/html
 #     src: "{{NFS_SERVER_IP_PRIVATE}}:/var/www/html"
 #     state: mounted
 #     fstype: nfs
 #     opts: nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800

  - name:
    shell: mount "{{NFS_SERVER_IP_PRIVATE}}:/var/www/html /var/www/html"
  - name: Editamos el archivo /etc/fstab para que al iniciar la máquina se monte automáticamente el directorio compartido por NFS.
    shell: echo "{{NFS_SERVER_IP_PRIVATE}}:/var/www/html /var/www/html  nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0" >> -a /etc/fstab