---
- name: Playbook para instalar  wordpress
  hosts: front
  become: yes

  tasks: 

  - name: Añadimos las variables
    ansible.builtin.include_vars:
      ./variables.yml

  - name: Actualizar los repositorios
    apt:
      update_cache: yes

  - name: Instalamos el cliente nfs
    apt:
      name: nfs-common
      state: present

  - name: Montamos el directorio compartido
    ansible.posix.mount:
      path: /var/www/html
      src: "{{NFS_SERVER_IP_PRIVATE}}:/var/www/html"
      state: mounted
      fstype: nfs
      opts: nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
