---
- name: Playbook para instalar la pila nfs
  hosts: nfs
  become: yes

  tasks:

  - name: Actualizar los repositorios
    apt:
      update_cache: yes

  - name: Instalación nfs server
    apt:
      name: nfs-kernel-server

  - name: Creamos el directorio
    ansible.builtin.file:
      path: /var/www/html
      state: directory
      mode: 0755
      owner: nobody
      group: nogroup

  - name: Clonamos el repositorio
    git:
      repo: https://github.com/Daniel-Magana512/practica9V.git
      dest: /tmp/archivos

  - name: Pasamos el archivo de conf a /etc/exports
    copy:
      src: /tmp/archivos/fase2/conf/exports
      dest: /etc/exports
      remote_src: yes
      
  - name: Eliminamos los archivos clonados innecesarios.
    file:
      path: /tmp/archivos

  - name: Reiniciamos el servidor servidor nfs
    service:
      name: nfs-kernel-server
      state: restarted 
